### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by ethsmith** [egojump/ACGCard#2]
When I launched it in the editor all the assets were broken. The only error I got, however, was that it couldn't load the map MainMenu and I also had the extended standard library.

**Comment by uu-z** [comment]
How did you start this project？I means, do you use the below command? 
`git lfs clone https://github.com/egojump/ACGCard`.

**Comment by ethsmith** [comment]
Reinstalled and it worked. Was on my end. Thanks for the quick response!
